allowBuilds:
  esbuild: true
  spawn-sync: true
  vue-demi: true

overrides:
  tar: ">=7.5.21"
  tmp: ">=0.2.6"
  adm-zip: ">=0.6.1"
  shell-quote: ">=1.9.0"
  uuid@<11.1.1: ^11.1.1
  brace-expansion@^1: ^1.1.21
  brace-expansion@^2: ^2.1.7
  brace-expansion@^5: ^5.0.12
